export const queryKeys = {
  user: "user",
  banner: "banner",
  song: "song",
  trend: "trend",
  event: "event",
  artist: "artist",
  producer: "producer",
  dj: "dj",
  comedian: "comedian",
  users: "users",
  comedy: "comedy",
  playlist: "playlist",
  book: "book",
  beat: "beat",
  mix: "mix",
  analytics: "analytics",
  genre: "genre",
};
